Cleanup fix for region being dropped in signup since e6f5ca1
goclimate/goclimate pull request #473
Opened 2021-02-11 10:57 UTC by stefanlindbohm

Cleans up from quick fix in 851756f.

A few learnings:

- Passing a single object to a path helper that doesn't take an ID
  replaces the implicit use of params for that request (in this case
  causing the disappearance of the region param in the path)
- With routes for the same resources defined twice, form_with seems
  confused about which of them to use, even when each action is only
  present in either of the two routes. Specifying both model and url
  solves this.

2021-02-11 14:18 UTC, emmabckstrm requested changes
Nice work! This really cleans everything up as it mostly should be! However, it introduces the signup url having `campaign=` if there is no value for the campaign and I feel that would look unprofessional (I tested it locally). My suggestion is to bring back the 

```
    query_params = {
      lifestyle_footprint: @footprint
    }
    query_params[:campaign] = campaign_param unless campaign_param.blank?
 ```
 
 part, if there is no one liner way of altering as it is now

2021-02-11 15:04 UTC, kallenilver commented
May I also add a test to the wishlist so that we can make sure this does not happen again?

2021-02-16 09:50 UTC, stefanlindbohm commented
@emmabckstrm 

> Nice work! This really cleans everything up as it mostly should be! However, it introduces the signup url having `campaign=` if there is no value for the campaign and I feel that would look unprofessional (I tested it locally). My suggestion is to bring back the
> 
> ```
>     query_params = {
>       lifestyle_footprint: @footprint
>     }
>     query_params[:campaign] = campaign_param unless campaign_param.blank?
> ```
> 
> part, if there is no one liner way of altering as it is now

Haha, I thought I did just that but messed up before I made the commit. Fixed now (using `.presence` and no conditionals nor the stuff I did that didn't do anything at all).

@kallenilver 

> May I also add a test to the wishlist so that we can make sure this does not happen again?

Added to the integration test!

2021-02-16 13:14 UTC, emmabckstrm approved these changes
⭐ ⭐ ⭐

2021-02-16 13:23 UTC, kallenilver approved these changes
🥳

2021-02-16 16:07 UTC, merged