rename business calculator to data collection
goclimate/goclimate pull request #611
Opened 2021-11-16 14:31 UTC by nanditagoclimate

2021-11-19 19:30 UTC, nanditagoclimate commented on app/views/admin/data_collections/_form.html.erb
>      <%= form.button class: 'button button-cta', type: 'button', 'data-disable-with': 'Please wait..', 'data-action': 'data-collection-form#submit' %>
On clicking  'create data collection', the form is being created in database, by the app is not going back to listing page. Unable to figure out why. Need @emmabckstrm 's help here please

2021-11-22 10:01 UTC, stefanlindbohm approved these changes
Good work tracking all usage points down!

I'm adding mostly comments that are down to taste so I'll let you decide what to pick up on and what to leave as is.

2021-11-22 10:01 UTC, stefanlindbohm commented on yarn.lock
> +  integrity sha512-kFXwYvHe5rix25uwueBxC569o53J6TpnGu0BEEn+6Lhl2vsnAumRFWEBhDft1fwyo6m1r4i+RqA4+163FpeFcA==
If I'm gonna be super picky, this is unrelated to the changes of this PR and should be done separately.

2021-11-22 10:19 UTC, emmabckstrm requested changes
Really, really great work! I agree with Stefan's point on pluralization of `DataCollection`. 

I did also test the branch locally and I was not able to save a DataCollection::Form from Admin view, I tried with an existing calculator that was in draft status. See error below.
<img width="1440" alt="Screenshot 2021-11-22 at 11 07 15" src="https://user-images.githubusercontent.com/8473077/142843443-729ea05a-4b35-49eb-83f8-b88b7fd2a944.png">

I also tried to create a new calculator, which worked fine, but I can't seem to add any questions to my sections, and I don't get any apparent errors as a user. So there seem to be something fishy with the questions. Other than that I seem to be able to use the form as usual :blush:

Small thing: In the admin menu, the Data Collection Form item is not highlighted when I have clicked on it. This is fixed in file `app/views/layouts/admin.html.erb` on line 65, where it's looking for controllers with name `business_calculators`.

2021-11-22 10:19 UTC, emmabckstrm commented on app/models/data_collections/form.rb
> +module DataCollections
I agree

2021-11-30 04:48 UTC, merged