Allows us to publish a GoClimate app on the fortnox app store
goclimate/goclimate pull request #661
Opened 2022-02-28 16:09 UTC by kallenilver

I did a quick first iteration of an integration with fortnox, so that we can publish an app in their app store and offer our accounting engine services there. 

This flow basically just allows a fortnox user to give us access to their bookkeeping, and saves the auth tokens in our back end, so that we in a later stage can get back to the customers with a price estimate.

2022-03-08 07:16 UTC, axelsson requested changes
Unsure how much of a poc this is so just ignore the comments that you dont feel are relevant at this stage.

2022-03-08 07:16 UTC, axelsson commented on app/controllers/fortnox_customers_controller.rb
> +    fortnox_params = fortnox_api.connect(params['code'])
Not sure how we're usually working with logging/error handling but i accidentaly tested the flow without having the env-variables added and no error whatsoever was thrown; the row in the database was added without access/refreshtoken and the user got to the "done"-page. Might be good to have some sort of handling so that we and the users notices if something's wrong with the api-connection.

2022-03-08 07:16 UTC, axelsson commented on app/views/fortnox_customers/_form.html.erb
> +        <div class="t:flex justify-between">
indentation

2022-03-08 07:16 UTC, axelsson commented on db/migrate/20220226205735_create_fortnox_customers.rb
> +      t.string :company_name
company name doesnt seem to be used/set?

2022-03-08 07:16 UTC, axelsson commented on app/views/fortnox_customers/_form.html.erb
> +      </div>
Shouldn't these fields be required? Now you can successfully submit the form without any data at all.

2022-03-10 10:28 UTC, kallenilver commented on app/controllers/fortnox_customers_controller.rb
> +    fortnox_params = fortnox_api.connect(params['code'])
Great thinking, I'm a bit too fast sometimes :) I've added the not null to the api-columns so that we will throw an exception if we don't get them from the api. That way at least we will be notified if something is up.

2022-03-10 10:28 UTC, kallenilver commented on db/migrate/20220226205735_create_fortnox_customers.rb
> +      t.string :company_name
Good catch, removed it now!

2022-03-10 10:28 UTC, kallenilver commented on app/views/fortnox_customers/_form.html.erb
> +      </div>
Good thinking, I made name and email html5 required now. Phone is ok to skip I think.

2022-03-14 11:21 UTC, axelsson approved these changes
Good work, let's see if fortnox wanna try it out! =)

2022-03-15 07:28 UTC, merged