Simple calculator API endpoint
goclimate/goclimate pull request #781
Opened 2023-04-09 20:11 UTC by kallenilver

2023-04-14 07:04 UTC, axelsson requested changes
Najs, stort jobb! 💪 

Har mest kommenterat frågor för att jag inte fattar hur det funkar men hittade lite konstigheter också:

Testade att göra request mot `http://localhost:3000/api/v1/business_simple_calculations?session_id=123&country=us&employee_count=3&calculation_period=2021` och då ser jag att loggen spottar ur sig 
`Unpermitted parameters: :employee_count, :subdomain, :format. Context: { controller: Api::V1::BusinessSimpleCalculationsController, action: create, request: #<ActionDispatch::Request:0x00007fbf6f844618>, params: {"session_id"=>"123", "country"=>"us", "employee_count"=>"3", "calculation_period"=>"2021", "subdomain"=>false, "format"=>:json, "controller"=>"api/v1/business_simple_calculations", "action"=>"create"} }`
i väldigt röd text, vet inte om det är jag eller koden som är ute o cyklar här?

Är lite sugen på nåt simplare namn för endpointen istället för `business_simple_calculations`, ev t ex `business_calculation`? Tänker främst för att vi inte heller har nån "business advanced" eller så.

Varken `other_co2e` eller `other_emissions` verkar funka för att lägga på antal kg emissions (får error när jag använder `other_emissions`).

2023-04-17 11:09 UTC, kallenilver commented on app/controllers/business/climate_reports_controller.rb
> +      if @report.country == 'gb' || @report.country == 'us'
Jag tror det tyvärr

2023-04-17 11:11 UTC, kallenilver commented on app/models/climate_report_calculation.rb
> +  def other_no_coffee_emissions
Nej, exakt. I den nuvarande kalkylen så ingår kaffe (eller `employee_emissions`) i `other_emissions`. Nu har vi brutit ut det och lägger det i meals istället, därav distinktionen. Men som sagt det där får vi ta bort när vi tar bort gamla kalkylatorn, då borde den där bara heta other_emissions.

2023-04-17 11:14 UTC, kallenilver commented on app/models/climate_report_calculation.rb
> +  def perform_calculation
för att den kallas från en statisk metod i `new_from_climate_report`, då kan den inte vara privat för ett object.

2023-04-17 12:27 UTC, kallenilver commented on app/models/climate_report_calculation.rb
> +      electronics_emissions + business_travel_emissions + car_emissions
Jepp, håller med. Jag la faktiskt in en vehicle_use metod som bara kallade car_emissions, men kändes lite väl redundant så tog bort den och så blev det så här. Tror jag ändå föredrar det här.

2023-04-17 12:31 UTC, kallenilver commented on app/models/climate_report_calculation.rb
> +    if !climate_report.use_purchased_phones_averages.nil? && climate_report.use_purchased_phones_averages
Yes, när den gamla försvinner så kommer alltid `use_purchased_phones_averages` vara satt.

2023-04-17 12:32 UTC, kallenilver commented on app/serializers/api/v1/climate_calculation_serializer.rb
> +                    value: 0
Ja, jag tolkade Andrea och Don som att vi kanske ska lägga till något där framåt. Men om det inte dyker upp något där så borde vi ta bort det (och även uppdatera API-specen).

2023-04-17 12:33 UTC, kallenilver commented on config/country_wise_climate_constants.yml
> +  home_office_per_fte_emissions: 1.0806048 # kWh per day WFH - days WFH (assumed 20% of total of year)-Location based EF Sweden s2 & s3 (ones gotten by GC)
Jag kan skriva till Andrea och Don att de får återkomma med uppdaterade siffror innan lansering.

2023-04-17 12:41 UTC, kallenilver commented
> Är lite sugen på nåt simplare namn för endpointen istället för `business_simple_calculations`, ev t ex `business_calculation`? Tänker främst för att vi inte heller har nån "business advanced" eller så.

Mmm, funderade en del på det där, men business_calculations kanske är bättre ändå, jag fixar.

2023-04-17 12:42 UTC, kallenilver commented
> Varken `other_co2e` eller `other_emissions` verkar funka för att lägga på antal kg emissions (får error när jag använder `other_emissions`).

Ops, bra spottat. Jag fixar!

2023-04-17 12:43 UTC, kallenilver commented
> Testade att göra request mot
> `http://localhost:3000/api/v1/business_simple_calculations?session_id=123&country=us&employee_count=3&calculation_period=2021` och då ser jag att loggen spottar ur sig
> `Unpermitted parameters: :employee_count, :subdomain, :format. Context: { controller: Api::V1::BusinessSimpleCalculationsController, action: create, request: #<ActionDispatch::Request:0x00007fbf6f844618>, params: {"session_id"=>"123", "country"=>"us", "employee_count"=>"3", "calculation_period"=>"2021", "subdomain"=>false, "format"=>:json, "controller"=>"api/v1/business_simple_calculations", "action"=>"create"} }`
> i väldigt röd text, vet inte om det är jag eller koden som är ute o cyklar här?

Ja, så är det för mig också. Employee count kommer lösa sig när vi tar bort gamla kalkylatorn, men format och subdomain kommer alltid skickas in. Känns inte heller rätt att permitta dem in i modellen även fast det inte skadar så gör de ingen nytta där heller. Tycker vi låter det vara så här.

2023-04-17 13:47 UTC, axelsson approved these changes
👍 Fint fixat!

Enda grejen jag såg var kvar är waste & water som jag trodde vi skulle skippa nu. Annars är det väl bara att tuta och köra 🚗

2023-04-17 17:02 UTC, merged